name: sierraitgroup
favicon: null
layout_spectrum: 0.2379
typography_spectrum: 1
title: San Francisco I.T. Support
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#333436'
    - '#0085d5'
    - '#54abe2'
    - '#a8d7e5'
    - '#4d6576'
  brandStrength: 0.1875
  lightness: 0.6875
  saturation: 0.9375
  rhythmicContrast: 1
purpose: []
