name: sierraitgroup
favicon: null
layout_spectrum: 0.1090057275723666
typography_spectrum: 0.21117612393572927
title: San Francisco I.T. Support
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191a1e'
    - '#70171b'
    - '#8c4e1b'
    - '#bc9143'
    - '#e3df7c'
  brandStrength: 0.25
  lightness: 0.6875
  saturation: 0.9375
  rhythmicContrast: 0.5
purpose: []
