name: sierraitgroup
favicon: null
layout_spectrum: 0.1090057275723666
typography_spectrum: 0.21117612393572927
title: San Francisco I.T. Support
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3598573917988688
  lightness: 0.11794121842831373
  saturation: 0.4703162219375372
  rhythmicContrast: 0.6567739089950919
purpose: []
